require "simplecov"
SimpleCov.start
require "minitest/autorun"
require "minitest/pride"
require "./lib/futbol_data"
require "./lib/game_statistics"
require "./lib/league_statistics"
require "./lib/season_statistics"
require "./lib/team_statistics"
require "csv"
require "mocha/minitest"
